language: android
dist: trusty
sudo: required
jdk:
  - oraclejdk8
group: edge

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-support
    - extra-android-m2repository
env:
  global:
    - TERM=dumb
before_script:
  - export DATE=$(date)
  - export VERSION=$(date --date="$DATE" +'%Y%m%d%H%M%S')
script:
  - ./gradlew clean build